### ISSUE TITLE
Menu builder should pull the authority list from an API

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/sprout-platform#109]
Currently the "admin" authority is the only one available in the menu builder, menu item editor.  

We may need an additional backend API to retrieve the list of known authorities.  

Menu editing - 
![image](https://user-images.githubusercontent.com/2660839/137364273-4f66ec32-3877-4409-a4da-fd90d5702017.png)

**Comment by ketankanhasoft** [comment]
Hello jeremy,

Just small question regarding this task, Now we will use authority dropdown here, do we have a multiselect dropdown here OR we just need to use single select for authorities?

**Comment by ketankanhasoft** [comment]
![147373762-24ae86f3-04c8-465d-ace6-451310f379b1 png (2457×1518)](https://user-images.githubusercontent.com/24564038/147531355-196579a9-d6f2-431e-badc-2b3ec9f3ecee.png)

**Comment by jdbranham** [comment]
Authorities == Privileges  

Maybe we should rename "Privileges" on the Permissions editor to be "Authorities" to make it match.  🤔

**Comment by ketankanhasoft** [comment]
Hi @jdbranham 
I have created PR.
https://github.com/savantly-net/sprout-platform/pull/158
