### ISSUE TITLE
When there are many menu items, it's difficult to edit them

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/sprout-platform#133]
After adding many menu items, especially with sub menus, it's difficult to scroll and see exactly where items are lined up.   

We should modify the styling to shift the menu editor to the left, instead of being in the middle of the page.  
When a menu item has children, we should make it collapsable to hide the children.   

Current state -  
![image](https://user-images.githubusercontent.com/2660839/140652612-8dd1c0d5-0800-45da-90f1-310dbce7fa7e.png)

Example of how this might look -  
![image](https://user-images.githubusercontent.com/2660839/140652794-22a2598a-660f-4f58-a205-3ea515991018.png)

**Comment by ketankanhasoft** [comment]
Hi jeremy 

I create a pull request for this task and still there are more issues related to menu so i also included those changes in this pull request.

https://github.com/savantly-net/sprout-platform/pull/151
