### ISSUE TITLE
There should be styling in the Markdown panel

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/sprout-platform#141]
The markdown panel visualization should be rendering some default styles, but they are being overridden by something.  

You can see in this image, the rendered elements do not have the correct styles applied to them.

![image](https://user-images.githubusercontent.com/2660839/142971806-21da74e6-5960-4c71-b66f-70ad1b34e1a9.png)

It should look more like this [GitHub rendering]  

# Title  
## Subtitle

For markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)
   
> test   

-  one
-  two

<hr/>

Steps to reproduce -   

-  Log in
-  Click the Configuration menu
-  Click "Manage Dashboards"
-  Click "Create Dashboard"
-  Click "Add Panel" 
-  Add some markdown in the Display tab

![image](https://user-images.githubusercontent.com/2660839/142972154-40b876c6-63a9-4f97-99fa-b6e0f99fa8a7.png)

![image](https://user-images.githubusercontent.com/2660839/142972198-81c964a4-8f06-4357-b556-5f300219e29e.png)

**Comment by ketankanhasoft** [comment]
hi jeremy

I created pull request for this task.

https://github.com/savantly-net/sprout-platform/pull/148
