### ISSUE TITLE
Should be able to navigate to a specific version of a dashboard

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/sprout-platform#142]
When managing the dashboards, we should be able to click the `version` number to navigate to the specific dashboard version.  
The client url should look like this -  `/d/{uid}` 

![image](https://user-images.githubusercontent.com/2660839/142975015-04827b4e-76d1-49af-9ff8-1914d2356602.png)

**Comment by ketankanhasoft** [comment]
hi jeremy

I created pull request for this task.

https://github.com/savantly-net/sprout-platform/pull/147
