### ISSUE TITLE
"No privileges available" in the permission editor

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/sprout-platform#163]
When a role contains an empty array for the current privileges, we display a message "Sorry, no privileges available".  
We should instead show the list of available privileges, so they can be added to the role.   

Context -  
![image](https://user-images.githubusercontent.com/2660839/147955358-c0dd91ed-2086-43e0-9f8f-67b0df12788a.png)

**Comment by ketankanhasoft** [comment]
I created PR for this task
https://github.com/savantly-net/sprout-platform/pull/166

**Comment by jdbranham** [comment]
Ketan - 
Can you confirm all privileges are shown when any Role is selected?  I am not seeing a privilege list when certain Roles are selected -   

![image](https://user-images.githubusercontent.com/2660839/150027121-d07e2d71-a002-4347-8a9e-eaaf896e7697.png)
