### ISSUE TITLE
Add properties to account API

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/sprout-platform#165]
Current the account API returns this -  

```
{
  "name": "string",
  "authorities": [
    "string"
  ]
}
```

It should return 
- userId
- username
- displayName
- emailAddress
- firstName
- lastName
- roles

This is blocking #164

**Comment by ketankanhasoft** [comment]
Hello @jdbranham ,

any update regarding this task, please let me know if this one is completed your side.

Thanks.
