### ISSUE TITLE
Allow changing dashboard name

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/sprout-platform#171]
When the 'gear' icon is clicked on a dashboard, we should be able to change the name of the dashboard.   
We may open a modal with different dashboard settings available. [the only changeable setting currently is the name]  

![image](https://user-images.githubusercontent.com/2660839/151491461-ae756290-c99c-4a3f-bd13-7ba033aadbc1.png)

**Comment by ketankanhasoft** [comment]
hey @jdbranham 
update dashboard name i have to try using ​/api​/dashboards​/db api, also have pass id for the current setting name but it's not working can you please check it, let me know if I'm doing wrong.

[dashboard-json.txt](https://github.com/savantly-net/sprout-platform/files/7971716/dashboard-json.txt)



![image](https://user-images.githubusercontent.com/24564038/151815575-b6a66986-eec6-4672-8aa7-182b4ba853a4.png)

**Comment by jdbranham** [comment]
I'm adding an integration test for this.

**Comment by ketankanhasoft** [comment]
Hey @jdbranham 
i have checked it today and when I'm updating any dashboard setting name, it will create a new duplicate version with a new updated name.
so this flow is right?
