### ISSUE TITLE
Clean up UI build warnings

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/sprout-platform#49]
### Easy fixes, but there's a bunch -  

Run `rush lint` to see the output.  

![image](https://user-images.githubusercontent.com/2660839/142457538-30495886-ed43-49b1-a6da-ac4654260115.png)

**Comment by jdbranham** [comment]
The list is probably out of date.   
@ketankanhasoft - 
Is this something you could take a look at?

**Comment by ketankanhasoft** [comment]
Hi jeremy

I created pull request for this, it contain lot of files.

https://github.com/savantly-net/sprout-platform/pull/150

**Comment by ketankanhasoft** [comment]
Hey, @jdbranham also I have hidden some warnings and pushed more code on cleanup_warnings_by_ketan branch, please check it and let me know your feedback.

**Comment by jdbranham** [comment]
I think this one is merged now

**Comment by ketankanhasoft** [comment]
Hello @jdbranham 
I have created another PR to hide some more warnings, please review it and let me know your feedback.

https://github.com/savantly-net/sprout-platform/pull/174
