### ISSUE TITLE
Replace '@savantly/sprout-ui' dependency with '@sprout-platform/ui'

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/sprout-platform#58]
The dependence on '@savantly/sprout-ui' should be removed, and missing functionality added to  '@sprout-platform/ui'.    

This issue is eligible for a bounty. If you're interested, message me and let's discuss an appropriate amount.  
Thanks!

There are 11 references in the backend projects -  
![image](https://user-images.githubusercontent.com/2660839/114098232-aff46080-9886-11eb-8d45-344c3f0f4520.png)

And 72 references in the frontend modules - 
![image](https://user-images.githubusercontent.com/2660839/114098307-c8fd1180-9886-11eb-92f0-6e1e5ba2e21b.png)

**Comment by jdbranham** [comment]
Ketan - 
Let's move only the necessary components from  `@savantly/sprout-ui` to `@sprout-platform/ui`, so we can remove the dependency on  `@savantly/sprout-ui`

**Comment by jdbranham** [comment]
Hi @ketankanhasoft - it looks like we've moved many components from `@savantly/sprout-ui` to `@sprout-platform/ui`  

Are we sure all those components are necessary? 🤔  We want to keep `@sprout-platform/ui`  as small as possible.   

Let's prefer to modify the main webapp to use an existing component from `@sprout-platform/ui`  rather than copying a component in from `@savantly/sprout-ui`   

Let's only bring a component into `@sprout-platform/ui` if we don't have an existing component that works. And when we add a component, let's keep it as minimal as possible.   
The goal is to keep `@sprout-platform/ui` a small and concise library.

**Comment by ketankanhasoft** [comment]
Hey, @jdbranham
I have pushed code again on the issue_58_replace_sprout_platform_ui branch, I have copied only which components are needed on @sprout-platform/ui.
can you please check it and share your feedback.

**Comment by ketankanhasoft** [comment]
Hey @jdbranham 
Here is PR, https://github.com/savantly-net/sprout-platform/pull/172
