### ISSUE TITLE
"Item not found" when creating a new Issue

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/sprout-platform#84]
When a new issue is created, it navigates to the details view for the issue, but redux doesn't contain the new issue yet, so it gives an error.   
Should we fetch the issue every time we navigate to the details page, and ignore what's in redux?

![image](https://user-images.githubusercontent.com/2660839/122581658-e8e64980-d01c-11eb-90ec-1c44b290c176.png)

**Comment by manoj-savantly** [comment]
@jdbranham This doesn't seem like an issue anymore. Can you please check and confirm?

**Comment by jdbranham** [comment]
The `EntityManager` is responsible for loading the state.  
When we access the "View Item" page of an entity, it uses the `EntityItemIndexPage` component to render the item view.  
It appears there is sometimes a race condition, or the new entity is not present in the state, so it throws this error.   
See here for the implementation of the "view item" page.   
https://github.com/savantly-net/sprout-platform/blob/master/frontend/libs/ui/src/components/Entity/EntityItemIndexPage.tsx#L54

When viewing a single item, we should fetch it from the `EntityService` instead of the `EntityStateProvider`.  

The `EntityService` contains a `getById` function -  
https://github.com/savantly-net/sprout-platform/blob/master/frontend/libs/api/src/entity/service.ts#L13

The `EntityItemEditPage` is already using the `EntityService` to fetch the item by ID, so we can implement it the same way.  
https://github.com/savantly-net/sprout-platform/blob/master/frontend/libs/ui/src/components/Entity/EntityItemEditPage.tsx#L40

Essentially we will use this in the `EntityItemIndexPage` -  

```
  useMemo(() => {
    if (!item) {
      entityService
        .getById(itemId)
        .then((response) => {
          setItem(response.data);
          setError('');
        })
        .catch((err) => {
          setError(err.message || err.detail || 'An error occurred while retreiving the item');
        });
    }
  }, [itemId, item]);
```

**Comment by ketankanhasoft** [comment]
hi jeremy

I created pull request for this task.

https://github.com/savantly-net/sprout-platform/pull/149
