### ISSUE TITLE
Add a "use this version" to the dashboard management page

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/sprout-platform#86]
Saved dashboards create new versions which are listed in the dashboard management page.  
There are links to view the old versions, but not a way to re-apply the old version as a new version.  

Currently when a dashboard is listed in the menu, it always references the latest version.  
This is ok, when an older version is selected as "use this version", it can re-save the dashboard with the old definition - creating a new version that is the same as the selected old version.

Dashboard API - https://sprout-server.herokuapp.com/swagger-ui/index.html?configUrl=../v3/api-docs/swagger-config#/dashboards-api

![image](https://user-images.githubusercontent.com/2660839/122582973-5f377b80-d01e-11eb-8a74-b876fb806e3d.png)

**Comment by manoj-savantly** [comment]
@jdbranham A quick question, how do a user create a version of the dashboard page?

**Comment by jdbranham** [comment]
Every time a dashboard is changed and saved, it becomes a new version.

I think the "use this version" function can take the selected dashboard definition, and save it as the current dashboard.
This way there's still a linear history of the dashboard versions.
