### ISSUE TITLE
Add a User Manager screen

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/sprout-platform#90]
There should be a `Users` option under the `Configuration` menu that navigates to a `User Manager`  

The new User Manager page should:  
- display all the registered users  
- allow creating new basic auth users
- allow editing of a user's roles

The new feature can be added here -  
https://github.com/savantly-net/sprout-platform/tree/master/frontend/apps/webapp/src/features

The new menu item here -  
https://github.com/savantly-net/sprout-platform/blob/master/frontend/apps/webapp/src/features/navigation/defaultNavTree.ts

The api for this doesn't exist yet - watch #89 

![image](https://user-images.githubusercontent.com/2660839/122680354-4a8cec00-d1b4-11eb-9df7-925a5e9b1a05.png)

**Comment by ketankanhasoft** [comment]
@jdbranham 

https://github.com/savantly-net/sprout-platform/pull/154

Here is the PR for the user management screen.
